// This file is AUTO GENERATED by CMake.
#pragma once
#include "SDL_video.h"
const static char* FILENAME_CONFIG = "config.xml";
const static char* FILENAME_SCORES = "hiscores.xml";
const static char* FILENAME_SCORES_JAPAN = "hiscores_jap.xml";
const static char* FILENAME_TTRIAL = "hiscores_timetrial.xml";
const static char* FILENAME_TTRIAL_JAPAN = "hiscores_timetrial_jap.xml";
const static char* FILENAME_CONT   = "hiscores_continuous.xml";
const static char* FILENAME_CONT_JAPAN   = "hiscores_continuous_jap.xml";
const static int SDL_FLAGS = SDL_HWSURFACE | SDL_DOUBLEBUF;
    